# Title: Assignment 3.2 oneal_composers.yaml
# Author: Professor Krasso
# Date: 11/02/2022
# Modified By: Chad ONeal
# Description: composers.yaml file

openapi: "3.0.0"
info:
  title: Composer's API
  version: 1.0.0

servers:
  - url: https://localhost:3000/
    description: Main server  
paths:
  /composers:
    get:
      tags:
        - Composers
      description: API for returning a list of all composers.
      summary: returns a list of composer documents
      responses:
        '200': #status code 
          description: json array of composer names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '500': #status code
          description: Server exception
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '501': #status code
          description: MongoDB exception
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      tags:
        - Composers
      description: API for adding a new composer
      summary: Creates and adds composer document
      requestBody:
        description: Composer information
        content:
          application/json:
            schema:
              required:
                - type
              properties:
                type:
                  type: string
      responses:
        '200': #status code
          description: composer added
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '500': #status code
          description: Server Exception
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '501': #status code
          description: MongoDB Exception
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /composers/{id}:
    get:
      tags:
        - Composers
      description: API for returning a composer by ID
      summary: returns a composers first and last name by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
          type: string
      responses:
        '200': #status code
          description: Composer document in JSON format
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '500': #status code
          description: Server Exception
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '501': #status code
          description: MongoDB Exception
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string